# spring.application.name=job-application-tracker
# server.port=8080

# # MongoDB Local
# # spring.data.mongodb.host=localhost
# # spring.data.mongodb.port=27017
# # spring.data.mongodb.database=jobtracker
# mongodb+srv://viraj_deshmukh:Viraj@123@jobtrackercluster.tr4ctdy.mongodb.net/jobtracker?retryWrites=true&w=majority&appName=JobTrackerCluster

# # Logging
# logging.level.org.springframework.data.mongodb=DEBUG
# logging.level.com.jobtracker=DEBUG

# # JSON Date Format
# spring.jackson.serialization.write-dates-as-timestamps=false

# # Error Messages
# server.error.include-message=always
# server.error.include-binding-errors=always

# New properties

spring.application.name=job-application-tracker

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://viraj_deshmukh:viraj123@jobtrackercluster.tr4ctdy.mongodb.net/jobtracker?retryWrites=true&w=majority&tlsAllowInvalidCertificates=true
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.jobtracker=DEBUG

spring.jackson.serialization.write-dates-as-timestamps=false

server.error.include-message=always
server.error.include-binding-errors=always