spring.application.name=job-application-tracker

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://viraj_deshmukh:Viraj%40123@jobtrackercluster.tr4ctdy.mongodb.net/jobtracker?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=true

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.jobtracker=DEBUG

spring.jackson.serialization.write-dates-as-timestamps=false

server.error.include-message=always
server.error.include-binding-errors=always