spring.application.name=job-application-tracker

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://viraj_deshmukh:viraj123@jobtrackercluster.tr4ctdy.mongodb.net/jobtracker?retryWrites=true&w=majority

spring.data.mongodb.ssl.enabled=true
spring.data.mongodb.ssl.invalid-hostname-allowed=true

spring.jackson.serialization.write-dates-as-timestamps=false

server.error.include-message=always
server.error.include-binding-errors=always